#!/usr/bin/env bash
# Build Windows .dll for x86_64 + aarch64 and copy the C header.
# Consumers call the three `lid_*` symbols via P/Invoke (C#) or any
# other FFI mechanism; results are JSON-encoded `IdentifyResult`.
#
# Prerequisites (one-time):
#
#   # Native build on Windows (recommended for shipping):
#   rustup target add x86_64-pc-windows-msvc aarch64-pc-windows-msvc
#
#   # OR cross-compile from macOS/Linux via the GNU targets + MinGW:
#   rustup target add x86_64-pc-windows-gnu aarch64-pc-windows-gnu
#   brew install mingw-w64        # macOS
#   apt install mingw-w64         # Debian/Ubuntu
#
# Set TOOLCHAIN=gnu to use the cross-compile path (default: msvc).
#
# Output (target/windows/):
#   x86_64/language_identifier_ffi.dll
#   aarch64/language_identifier_ffi.dll
#   include/language_identifier.h
set -euo pipefail

cd "$(dirname "$0")/../../.."

CRATE=language-identifier-ffi
TOOLCHAIN="${TOOLCHAIN:-msvc}"
OUT=target/windows

case "$TOOLCHAIN" in
  msvc) TRIPLES=(x86_64-pc-windows-msvc aarch64-pc-windows-msvc) ;;
  gnu)  TRIPLES=(x86_64-pc-windows-gnu  aarch64-pc-windows-gnu)  ;;
  *) echo "TOOLCHAIN must be 'msvc' or 'gnu'"; exit 2 ;;
esac

rm -rf "$OUT"
mkdir -p "$OUT/x86_64" "$OUT/aarch64" "$OUT/include"

echo "==> Building .dll for ${TRIPLES[*]}"
for triple in "${TRIPLES[@]}"; do
  cargo build --release --target "$triple" -p "$CRATE"
done

cp "target/${TRIPLES[0]}/release/language_identifier_ffi.dll" "$OUT/x86_64/"
cp "target/${TRIPLES[1]}/release/language_identifier_ffi.dll" "$OUT/aarch64/"

# MSVC also produces an import library (.dll.lib) — copy if present.
[[ -f "target/${TRIPLES[0]}/release/language_identifier_ffi.dll.lib" ]] && \
  cp "target/${TRIPLES[0]}/release/language_identifier_ffi.dll.lib" "$OUT/x86_64/"
[[ -f "target/${TRIPLES[1]}/release/language_identifier_ffi.dll.lib" ]] && \
  cp "target/${TRIPLES[1]}/release/language_identifier_ffi.dll.lib" "$OUT/aarch64/"

# Header is generated by build.rs into target/c-header/.
cp target/c-header/language_identifier.h "$OUT/include/"

echo
echo "Done. Artifacts:"
echo "  $OUT/x86_64/language_identifier_ffi.dll"
echo "  $OUT/aarch64/language_identifier_ffi.dll"
echo "  $OUT/include/language_identifier.h"
echo
echo "C# (P/Invoke) consumption:"
echo "  [DllImport(\"language_identifier_ffi\", CallingConvention = CallingConvention.Cdecl)]"
echo "  static extern IntPtr lid_identify(IntPtr input);"
echo "  [DllImport(\"language_identifier_ffi\")] static extern void lid_string_free(IntPtr s);"
echo "  // Marshal.PtrToStringUTF8(...) on the return, then JsonSerializer.Deserialize<IdentifyResult>()."
