[package]
name = "language-identifier-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[[bin]]
name = "language-identifier"
path = "src/main.rs"

[features]
default = []
ml-openlid = ["language-identifier/ml-openlid"]

[dependencies]
language-identifier = { path = "../language-identifier" }
serde_json = { workspace = true }
